#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export GOPATH=/Users/robbiet480/gocode
export PATH="$PATH:/usr/local/heroku/bin:$HOME/.rvm/bin:$GOPATH/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin/"
