#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias mosh='nocorrect mosh'
alias jq='nocorrect jq'
alias bower='noglob bower'
#alias ls='ls --color=auto'

function clip { [ -t 0 ] && pbpaste || pbcopy }

# The next line updates PATH for the Google Cloud SDK.
# source '/usr/local/bin/google-cloud-sdk/path.zsh.inc'

# The next line enables shell command completion for gcloud.
# source '/usr/local/bin/google-cloud-sdk/completion.zsh.inc'

source /Users/robbiet480/.iterm2_shell_integration.zsh

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
